# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ivan/Documents/QuantumWindow/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 810)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputGroupBox.sizePolicy().hasHeightForWidth())
        self.inputGroupBox.setSizePolicy(sizePolicy)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputHorizontalLayout = QtWidgets.QHBoxLayout()
        self.inputHorizontalLayout.setObjectName("inputHorizontalLayout")
        self.inputTableWidget = QtWidgets.QTableWidget(self.inputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputTableWidget.sizePolicy().hasHeightForWidth())
        self.inputTableWidget.setSizePolicy(sizePolicy)
        self.inputTableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputTableWidget.setAutoFillBackground(False)
        self.inputTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.inputTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.inputTableWidget.setProperty("showDropIndicator", False)
        self.inputTableWidget.setRowCount(8)
        self.inputTableWidget.setColumnCount(2)
        self.inputTableWidget.setObjectName("inputTableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.inputTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.inputTableWidget.setHorizontalHeaderItem(1, item)
        self.inputTableWidget.horizontalHeader().setVisible(True)
        self.inputTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.inputTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.inputTableWidget.horizontalHeader().setStretchLastSection(False)
        self.inputTableWidget.verticalHeader().setDefaultSectionSize(60)
        self.inputTableWidget.verticalHeader().setStretchLastSection(False)
        self.inputHorizontalLayout.addWidget(self.inputTableWidget)
        self.verticalLayout.addLayout(self.inputHorizontalLayout)
        self.inputParamsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.inputParamsHorizontalLayout.setObjectName("inputParamsHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.inputParamsHorizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.numberOfQubitsLabel = QtWidgets.QLabel(self.inputGroupBox)
        self.numberOfQubitsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numberOfQubitsLabel.setObjectName("numberOfQubitsLabel")
        self.gridLayout.addWidget(self.numberOfQubitsLabel, 1, 0, 1, 1)
        self.setZeroInputPushButton = QtWidgets.QPushButton(self.inputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setZeroInputPushButton.sizePolicy().hasHeightForWidth())
        self.setZeroInputPushButton.setSizePolicy(sizePolicy)
        self.setZeroInputPushButton.setObjectName("setZeroInputPushButton")
        self.gridLayout.addWidget(self.setZeroInputPushButton, 2, 0, 1, 2)
        self.numberOfQubitsSpinBox = QtWidgets.QSpinBox(self.inputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfQubitsSpinBox.sizePolicy().hasHeightForWidth())
        self.numberOfQubitsSpinBox.setSizePolicy(sizePolicy)
        self.numberOfQubitsSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numberOfQubitsSpinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numberOfQubitsSpinBox.setMinimum(1)
        self.numberOfQubitsSpinBox.setProperty("value", 3)
        self.numberOfQubitsSpinBox.setObjectName("numberOfQubitsSpinBox")
        self.gridLayout.addWidget(self.numberOfQubitsSpinBox, 1, 1, 1, 1)
        self.setSymbolicInputPushButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.setSymbolicInputPushButton.setObjectName("setSymbolicInputPushButton")
        self.gridLayout.addWidget(self.setSymbolicInputPushButton, 3, 0, 1, 2)
        self.setSymbolicByReAndImInputPushButton = QtWidgets.QPushButton(self.inputGroupBox)
        self.setSymbolicByReAndImInputPushButton.setObjectName("setSymbolicByReAndImInputPushButton")
        self.gridLayout.addWidget(self.setSymbolicByReAndImInputPushButton, 4, 0, 1, 2)
        self.inputParamsHorizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.inputParamsHorizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.inputParamsHorizontalLayout)
        self.horizontalLayout_2.addWidget(self.inputGroupBox)
        self.outputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputGroupBox.sizePolicy().hasHeightForWidth())
        self.outputGroupBox.setSizePolicy(sizePolicy)
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.outputGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.outputHorizontalLayout = QtWidgets.QHBoxLayout()
        self.outputHorizontalLayout.setObjectName("outputHorizontalLayout")
        self.outputTableWidget = QtWidgets.QTableWidget(self.outputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTableWidget.sizePolicy().hasHeightForWidth())
        self.outputTableWidget.setSizePolicy(sizePolicy)
        self.outputTableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.outputTableWidget.setAutoFillBackground(False)
        self.outputTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.outputTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.outputTableWidget.setProperty("showDropIndicator", False)
        self.outputTableWidget.setRowCount(8)
        self.outputTableWidget.setColumnCount(2)
        self.outputTableWidget.setObjectName("outputTableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.outputTableWidget.setHorizontalHeaderItem(1, item)
        self.outputTableWidget.horizontalHeader().setVisible(True)
        self.outputTableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.outputTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.outputTableWidget.horizontalHeader().setStretchLastSection(False)
        self.outputTableWidget.verticalHeader().setDefaultSectionSize(60)
        self.outputHorizontalLayout.addWidget(self.outputTableWidget)
        self.verticalLayout_8.addLayout(self.outputHorizontalLayout)
        self.outputGridLayout = QtWidgets.QGridLayout()
        self.outputGridLayout.setObjectName("outputGridLayout")
        self.outputFormLayout = QtWidgets.QFormLayout()
        self.outputFormLayout.setObjectName("outputFormLayout")
        self.setZeroOutputPushButton = QtWidgets.QPushButton(self.outputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setZeroOutputPushButton.sizePolicy().hasHeightForWidth())
        self.setZeroOutputPushButton.setSizePolicy(sizePolicy)
        self.setZeroOutputPushButton.setObjectName("setZeroOutputPushButton")
        self.outputFormLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.setZeroOutputPushButton)
        self.copyResultToInputPushButton = QtWidgets.QPushButton(self.outputGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyResultToInputPushButton.sizePolicy().hasHeightForWidth())
        self.copyResultToInputPushButton.setSizePolicy(sizePolicy)
        self.copyResultToInputPushButton.setObjectName("copyResultToInputPushButton")
        self.outputFormLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.copyResultToInputPushButton)
        self.setSymbolicByReAndImOutputPushButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.setSymbolicByReAndImOutputPushButton.setObjectName("setSymbolicByReAndImOutputPushButton")
        self.outputFormLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.setSymbolicByReAndImOutputPushButton)
        self.setSymbolicOutputPushButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.setSymbolicOutputPushButton.setObjectName("setSymbolicOutputPushButton")
        self.outputFormLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.setSymbolicOutputPushButton)
        self.outputGridLayout.addLayout(self.outputFormLayout, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.outputGridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.outputGridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.outputGridLayout)
        self.horizontalLayout_2.addWidget(self.outputGroupBox)
        self.gatesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gatesGroupBox.sizePolicy().hasHeightForWidth())
        self.gatesGroupBox.setSizePolicy(sizePolicy)
        self.gatesGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gatesGroupBox.setObjectName("gatesGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gatesGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.gatesGroupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -78, 252, 784))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pauliMatricesGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.pauliMatricesGroupBox.setObjectName("pauliMatricesGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pauliMatricesGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pauliMatricesGridLayout = QtWidgets.QGridLayout()
        self.pauliMatricesGridLayout.setObjectName("pauliMatricesGridLayout")
        self.pauliMatricesLabel = QtWidgets.QLabel(self.pauliMatricesGroupBox)
        self.pauliMatricesLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pauliMatricesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pauliMatricesLabel.setObjectName("pauliMatricesLabel")
        self.pauliMatricesGridLayout.addWidget(self.pauliMatricesLabel, 0, 0, 1, 2)
        self.pauliMatricesSpinBox = QtWidgets.QSpinBox(self.pauliMatricesGroupBox)
        self.pauliMatricesSpinBox.setMinimum(1)
        self.pauliMatricesSpinBox.setObjectName("pauliMatricesSpinBox")
        self.pauliMatricesGridLayout.addWidget(self.pauliMatricesSpinBox, 0, 2, 1, 1)
        self.pauliMatricesSigmaXPushButton = QtWidgets.QPushButton(self.pauliMatricesGroupBox)
        self.pauliMatricesSigmaXPushButton.setObjectName("pauliMatricesSigmaXPushButton")
        self.pauliMatricesGridLayout.addWidget(self.pauliMatricesSigmaXPushButton, 1, 0, 1, 3)
        self.pauliMatricesSigmaYPushButton = QtWidgets.QPushButton(self.pauliMatricesGroupBox)
        self.pauliMatricesSigmaYPushButton.setObjectName("pauliMatricesSigmaYPushButton")
        self.pauliMatricesGridLayout.addWidget(self.pauliMatricesSigmaYPushButton, 2, 0, 1, 3)
        self.pauliMatricesSigmaZPushButton = QtWidgets.QPushButton(self.pauliMatricesGroupBox)
        self.pauliMatricesSigmaZPushButton.setObjectName("pauliMatricesSigmaZPushButton")
        self.pauliMatricesGridLayout.addWidget(self.pauliMatricesSigmaZPushButton, 3, 0, 1, 3)
        self.verticalLayout_3.addLayout(self.pauliMatricesGridLayout)
        self.verticalLayout_9.addWidget(self.pauliMatricesGroupBox)
        self.hadamardGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.hadamardGroupBox.setObjectName("hadamardGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.hadamardGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hadamardGridLayout = QtWidgets.QGridLayout()
        self.hadamardGridLayout.setObjectName("hadamardGridLayout")
        self.hadamardLabel = QtWidgets.QLabel(self.hadamardGroupBox)
        self.hadamardLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hadamardLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hadamardLabel.setObjectName("hadamardLabel")
        self.hadamardGridLayout.addWidget(self.hadamardLabel, 0, 0, 1, 2)
        self.hadamardSpinBox = QtWidgets.QSpinBox(self.hadamardGroupBox)
        self.hadamardSpinBox.setMinimum(1)
        self.hadamardSpinBox.setObjectName("hadamardSpinBox")
        self.hadamardGridLayout.addWidget(self.hadamardSpinBox, 0, 2, 1, 1)
        self.hadamardPushButton = QtWidgets.QPushButton(self.hadamardGroupBox)
        self.hadamardPushButton.setObjectName("hadamardPushButton")
        self.hadamardGridLayout.addWidget(self.hadamardPushButton, 1, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.hadamardGridLayout)
        self.verticalLayout_9.addWidget(self.hadamardGroupBox)
        self.walshHadamardGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.walshHadamardGroupBox.setObjectName("walshHadamardGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.walshHadamardGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.walshHadamardVerticalLayout = QtWidgets.QVBoxLayout()
        self.walshHadamardVerticalLayout.setObjectName("walshHadamardVerticalLayout")
        self.walshHadamardPushButton = QtWidgets.QPushButton(self.walshHadamardGroupBox)
        self.walshHadamardPushButton.setObjectName("walshHadamardPushButton")
        self.walshHadamardVerticalLayout.addWidget(self.walshHadamardPushButton)
        self.horizontalLayout.addLayout(self.walshHadamardVerticalLayout)
        self.verticalLayout_9.addWidget(self.walshHadamardGroupBox)
        self.controlledNotGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.controlledNotGroupBox.setObjectName("controlledNotGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.controlledNotGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.controlledNotGridLayout = QtWidgets.QGridLayout()
        self.controlledNotGridLayout.setObjectName("controlledNotGridLayout")
        self.controlledNotControlQubitLabel = QtWidgets.QLabel(self.controlledNotGroupBox)
        self.controlledNotControlQubitLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.controlledNotControlQubitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlledNotControlQubitLabel.setObjectName("controlledNotControlQubitLabel")
        self.controlledNotGridLayout.addWidget(self.controlledNotControlQubitLabel, 0, 0, 1, 2)
        self.controlledNotControlSpinBox = QtWidgets.QSpinBox(self.controlledNotGroupBox)
        self.controlledNotControlSpinBox.setMinimum(1)
        self.controlledNotControlSpinBox.setObjectName("controlledNotControlSpinBox")
        self.controlledNotGridLayout.addWidget(self.controlledNotControlSpinBox, 0, 2, 1, 1)
        self.controlledNotTargetSpinBox = QtWidgets.QSpinBox(self.controlledNotGroupBox)
        self.controlledNotTargetSpinBox.setMinimum(1)
        self.controlledNotTargetSpinBox.setObjectName("controlledNotTargetSpinBox")
        self.controlledNotGridLayout.addWidget(self.controlledNotTargetSpinBox, 1, 2, 1, 1)
        self.controlledNotTargetLabel = QtWidgets.QLabel(self.controlledNotGroupBox)
        self.controlledNotTargetLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.controlledNotTargetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlledNotTargetLabel.setObjectName("controlledNotTargetLabel")
        self.controlledNotGridLayout.addWidget(self.controlledNotTargetLabel, 1, 0, 1, 2)
        self.controlledNotPushButton = QtWidgets.QPushButton(self.controlledNotGroupBox)
        self.controlledNotPushButton.setObjectName("controlledNotPushButton")
        self.controlledNotGridLayout.addWidget(self.controlledNotPushButton, 2, 0, 1, 3)
        self.verticalLayout_4.addLayout(self.controlledNotGridLayout)
        self.verticalLayout_9.addWidget(self.controlledNotGroupBox)
        self.controlledControlledNotGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.controlledControlledNotGroupBox.setObjectName("controlledControlledNotGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.controlledControlledNotGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.controlledControlledNotGridLayout = QtWidgets.QGridLayout()
        self.controlledControlledNotGridLayout.setObjectName("controlledControlledNotGridLayout")
        self.controlledControlledNotFirstControlLabel = QtWidgets.QLabel(self.controlledControlledNotGroupBox)
        self.controlledControlledNotFirstControlLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.controlledControlledNotFirstControlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlledControlledNotFirstControlLabel.setObjectName("controlledControlledNotFirstControlLabel")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotFirstControlLabel, 0, 0, 1, 2)
        self.controlledControlledNotTargetLabel = QtWidgets.QLabel(self.controlledControlledNotGroupBox)
        self.controlledControlledNotTargetLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.controlledControlledNotTargetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlledControlledNotTargetLabel.setObjectName("controlledControlledNotTargetLabel")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotTargetLabel, 2, 0, 1, 2)
        self.controlledControlledNotFirstControlSpinBox = QtWidgets.QSpinBox(self.controlledControlledNotGroupBox)
        self.controlledControlledNotFirstControlSpinBox.setMinimum(1)
        self.controlledControlledNotFirstControlSpinBox.setObjectName("controlledControlledNotFirstControlSpinBox")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotFirstControlSpinBox, 0, 2, 1, 1)
        self.controlledControlledNotTargetSpinBox = QtWidgets.QSpinBox(self.controlledControlledNotGroupBox)
        self.controlledControlledNotTargetSpinBox.setMinimum(1)
        self.controlledControlledNotTargetSpinBox.setObjectName("controlledControlledNotTargetSpinBox")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotTargetSpinBox, 2, 2, 1, 1)
        self.controlledControlledNotSecondControlLabel = QtWidgets.QLabel(self.controlledControlledNotGroupBox)
        self.controlledControlledNotSecondControlLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.controlledControlledNotSecondControlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlledControlledNotSecondControlLabel.setObjectName("controlledControlledNotSecondControlLabel")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotSecondControlLabel, 1, 0, 1, 2)
        self.controlledControlledNotSecondControlSpinBox = QtWidgets.QSpinBox(self.controlledControlledNotGroupBox)
        self.controlledControlledNotSecondControlSpinBox.setMinimum(1)
        self.controlledControlledNotSecondControlSpinBox.setObjectName("controlledControlledNotSecondControlSpinBox")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotSecondControlSpinBox, 1, 2, 1, 1)
        self.controlledControlledNotPushButton = QtWidgets.QPushButton(self.controlledControlledNotGroupBox)
        self.controlledControlledNotPushButton.setObjectName("controlledControlledNotPushButton")
        self.controlledControlledNotGridLayout.addWidget(self.controlledControlledNotPushButton, 3, 0, 1, 3)
        self.verticalLayout_5.addLayout(self.controlledControlledNotGridLayout)
        self.verticalLayout_9.addWidget(self.controlledControlledNotGroupBox)
        self.phaseGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.phaseGroupBox.setObjectName("phaseGroupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.phaseGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.phaseGridLayout = QtWidgets.QGridLayout()
        self.phaseGridLayout.setObjectName("phaseGridLayout")
        self.phaseDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.phaseGroupBox)
        self.phaseDoubleSpinBox.setMinimum(-99.0)
        self.phaseDoubleSpinBox.setObjectName("phaseDoubleSpinBox")
        self.phaseGridLayout.addWidget(self.phaseDoubleSpinBox, 1, 2, 1, 1)
        self.phasePushButton = QtWidgets.QPushButton(self.phaseGroupBox)
        self.phasePushButton.setObjectName("phasePushButton")
        self.phaseGridLayout.addWidget(self.phasePushButton, 2, 0, 1, 3)
        self.phasePhaseLabel = QtWidgets.QLabel(self.phaseGroupBox)
        self.phasePhaseLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phasePhaseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phasePhaseLabel.setObjectName("phasePhaseLabel")
        self.phaseGridLayout.addWidget(self.phasePhaseLabel, 1, 0, 1, 2)
        self.phaseControlSpinBox = QtWidgets.QSpinBox(self.phaseGroupBox)
        self.phaseControlSpinBox.setMinimum(1)
        self.phaseControlSpinBox.setObjectName("phaseControlSpinBox")
        self.phaseGridLayout.addWidget(self.phaseControlSpinBox, 0, 2, 1, 1)
        self.phaseControlQubitLabel = QtWidgets.QLabel(self.phaseGroupBox)
        self.phaseControlQubitLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phaseControlQubitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.phaseControlQubitLabel.setObjectName("phaseControlQubitLabel")
        self.phaseGridLayout.addWidget(self.phaseControlQubitLabel, 0, 0, 1, 2)
        self.verticalLayout_10.addLayout(self.phaseGridLayout)
        self.verticalLayout_9.addWidget(self.phaseGroupBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.gatesGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quantum Gates"))
        self.inputGroupBox.setTitle(_translate("MainWindow", "Input"))
        item = self.inputTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Re"))
        item = self.inputTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Im"))
        self.numberOfQubitsLabel.setText(_translate("MainWindow", "Number of qubits:"))
        self.setZeroInputPushButton.setText(_translate("MainWindow", "Set zero"))
        self.setSymbolicInputPushButton.setText(_translate("MainWindow", "Set symbolic"))
        self.setSymbolicByReAndImInputPushButton.setText(_translate("MainWindow", "Set symbolic by Re and Im"))
        self.outputGroupBox.setTitle(_translate("MainWindow", "Output"))
        item = self.outputTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Re"))
        item = self.outputTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Im"))
        self.setZeroOutputPushButton.setText(_translate("MainWindow", "Set zero"))
        self.copyResultToInputPushButton.setText(_translate("MainWindow", "<<  Copy result to input"))
        self.setSymbolicByReAndImOutputPushButton.setText(_translate("MainWindow", "Set symbolic by Re and Im"))
        self.setSymbolicOutputPushButton.setText(_translate("MainWindow", "Set symbolic"))
        self.gatesGroupBox.setTitle(_translate("MainWindow", "Gates"))
        self.pauliMatricesGroupBox.setTitle(_translate("MainWindow", "Pauli Matrices"))
        self.pauliMatricesLabel.setText(_translate("MainWindow", "Target qubit:"))
        self.pauliMatricesSigmaXPushButton.setText(_translate("MainWindow", "Apply SigmaX"))
        self.pauliMatricesSigmaYPushButton.setText(_translate("MainWindow", "Apply SigmaY"))
        self.pauliMatricesSigmaZPushButton.setText(_translate("MainWindow", "Apply SigmaZ"))
        self.hadamardGroupBox.setTitle(_translate("MainWindow", "Hadamard"))
        self.hadamardLabel.setText(_translate("MainWindow", "Target qubit:"))
        self.hadamardPushButton.setText(_translate("MainWindow", "Apply"))
        self.walshHadamardGroupBox.setTitle(_translate("MainWindow", "Walsh-Hadamard"))
        self.walshHadamardPushButton.setText(_translate("MainWindow", "Apply"))
        self.controlledNotGroupBox.setTitle(_translate("MainWindow", "Controlled NOT"))
        self.controlledNotControlQubitLabel.setText(_translate("MainWindow", "Control qubit:"))
        self.controlledNotTargetLabel.setText(_translate("MainWindow", "Target qubit:"))
        self.controlledNotPushButton.setText(_translate("MainWindow", "Apply"))
        self.controlledControlledNotGroupBox.setTitle(_translate("MainWindow", "Controlled Controlled NOT"))
        self.controlledControlledNotFirstControlLabel.setText(_translate("MainWindow", "Control qubit:"))
        self.controlledControlledNotTargetLabel.setText(_translate("MainWindow", "Target qubit:"))
        self.controlledControlledNotSecondControlLabel.setText(_translate("MainWindow", "Control qubit:"))
        self.controlledControlledNotPushButton.setText(_translate("MainWindow", "Apply"))
        self.phaseGroupBox.setTitle(_translate("MainWindow", "Phase"))
        self.phasePushButton.setText(_translate("MainWindow", "Apply"))
        self.phasePhaseLabel.setText(_translate("MainWindow", "Phase (fractions of pi):"))
        self.phaseControlQubitLabel.setText(_translate("MainWindow", "Control qubit:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
